### ISSUE TITLE
timeout in CuteChess = bug ?

### ISSUE THREAD

**Issue by tissatussa** [AndyGrant/Ethereal#158]
hi, i encounter in CuteChess that Ethereal is malfunctioning : it loses the game while timing out .. in CuteChess you can setup 2 engines and let them play any FEN at any time setting .. i gave 15 min + 10 sec .. i'm not sure the same occurs at other settings, but i guess so.  Note: LC0 has the same issue but its code differs ofcourse .. i use Ubuntu 20.04 and i compiled Ethereal in several versions .. they all have this issue : Ethereal runs out of time and the game is over !?

**Comment by AndyGrant** [comment]
Sounds like you are talking about a cutechess issue then and not an Ethereal issue. Are you using the GUI or the command line tool? If the command line tool, please paste the command you are passing, and maybe that will reveal something.

**Comment by tissatussa** [comment]
That could be ..!  I will try that .. now i'm using the GUI version .. indeed the log will show the Ethereal or CuteChess issue .. i will post a result log soon.

**Comment by AndyGrant** [comment]
Well so talking to me is somewhat fruitless. Even if your logfile shows that Ethereal is to blame, I'll disagree, since Ethereal plays tens of millions of games with no issue on other machines. I'm going to guess that either you are not passing the time controls in correctly, you are running other background processes that cause issues, or you are using more threads than your CPU.

I'm assuming you are using the master branch. If you forked the NNUE branch, I make no guarantees that it works.

**Comment by tissatussa** [comment]
thank you. i understand and i shall test it.  One note : most other engines (UCI) behave correctly in CuteChess.

**Comment by AndyGrant** [comment]
Ethereal does behave correctly under cutechess. 143,511,079 games played on my testing framework across many machines under many cutechess versions.

The fact that you said the issue occurs for Lc0 as well, indicates that the issue is not with the engines.
