### ISSUE TITLE
Error compiling Ethereal on MacOS

### ISSUE THREAD

**Issue by PaulJeFi** [AndyGrant/Ethereal#191]
I type ```make``` in the ```src``` directory. Here is what happened :

```
rm -f *.gcda pyrrhic/*.gcda nnue/*.gcda *.profdata *.profraw
clang -fprofile-instr-generate -O3 -std=gnu11 -Wall -Wextra -Wshadow -DNDEBUG -flto -DUSE_NNUE=0  -march=native -DUSE_POPCNT -DUSE_PEXT -DUSE_AVX2 -DUSE_AVX -DUSE_SSSE3 -fno-asynchronous-unwind-tables *.c pyrrhic/tbprobe.c -lpthread -lm -o Ethereal
./Ethereal bench > /dev/null 2>&1
llvm-profdata merge -output=ethereal.profdata *.profraw
/bin/sh: llvm-profdata: command not found
make: *** [pgo] Error 127
```

**Comment by AndyGrant** [comment]
You could try ``make basic``, since you don't have llvm-profdata on the env path. However, you probably have llvm-profdata-X, where X = the major version of your clang build. You could try to edit the makefile to replace ``llvm-profdata``. On linux systems, this is usually resolved via ``apt-get install llvm`` or ``yum install llvm``.

However, I don't make any guarantees as to whether Ethereal, either NNUE or HCE, actually works under MacOS. I do not have access to a Mac system, and I know that support for Mac is an issue with many other open source projects.

**Comment by AndyGrant** [comment]
Closed due to no response to further continue helping.
