### ISSUE TITLE
Ethereal Commercial VS Ethereal Free

### ISSUE THREAD

**Issue by ginkgo20** [AndyGrant/Ethereal#200]
What is the difference between commercial version of Ethereal and free version of Ethereal?

Is commercial version stronger than free version?

**Comment by AndyGrant** [comment]
Ethereal's commercial version uses NNUE, where as Ethereal's free version is a typical hand-crafted eval, coupled with an NN that only handles Pawns + Kings. The commercial version is significantly stronger, and comfortably sits as the 4th strongest engine in most major tournaments.

I went commercial with the introduction of NNUE. The reason being that training the networks, as an individual, required significantly more time and money than regular chess development. I could have just used the Stockfish tools and data and done it easily, but I opted to go my own way, in the hopes of learning something, and being able to contribute back some meaningful knowlege.

The site for Ethereal is http://chess.grantnet.us/Ethereal/. I don't have it linked here for some reason. I guess because marketing the commercial component has not been a major focus for me.

**Comment by penguingim1** [comment]
_Is it possible to separate NNUE file of Commercial version?_ 

_Is NNUE file of Commercial version usable for free version?_

**Comment by AndyGrant** [comment]
If you want to train your own NNUE file, you can easily compile Ethereal with the NNUE. However, short of that, there are no free NNUE versions for Ethereal.

**Comment by AndyGrant** [comment]
Good luck with that.

**Comment by ginkgo20** [comment]
If I extract NNUE file from Ethereal's commercial then is it possible to use it for stockfish engine?

If it is possible , Please tell me know which version of Stockfish is compatible with Ethereal's NNUE.

**Comment by AndyGrant** [comment]
No. The networks are not even remotely similar in structure or design.
