### ISSUE TITLE
pawnAttacks colour inversion

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/Ethereal#38]
Is this a bug or intentional?
```
 #define TB_PAWN_ATTACKS(square, color) (pawnAttacks((square), ~0ull, (!color)))
```
I don't understand. WHen I look at the definition of pawnAttacks() it looks correct (no colour inversion).

**Comment by AndyGrant** [comment]
This is intentional. From ``piece.h``
```
#define WHITE (0)
#define BLACK (1)
```

[However, from ``fathom/tbprobe.h``](https://github.com/AndyGrant/Ethereal/blob/4fe46d41a1ff1204835a4a8f62986815a35516e2/src/fathom/tbprobe.h#L194)
```
 *   true=white, false=black
```

So either Fathom uses ``WHITE=1, BLACK=0``, or something really wrong is going on internally, which seems unlikely since TB is not a massive failure for Ethereal.
