### ISSUE TITLE
SEE Pruning

### ISSUE THREAD

**Issue by ratosh** [AndyGrant/Ethereal#63]
Should SEE Pruning only be applied to movePicker.stage > STAGE_GOOD_NOISY? Is it trying to prune table move?

**Comment by ratosh** [comment]
Its pruning moves after GOOD_NOISY. 👍

**Comment by AndyGrant** [comment]
Haha, so this also catches me from time to time. It is weird to do comparisons when we think of the ttstage as stage 0, good as 1, ... 

Also worth nothing, the condition ``best > MATED_IN_MAX_PLY`` ensures that the TT move (and first tried legal move) is never pruned or reduced. Since best starts at -MATE.
