### ISSUE TITLE
Clarify the Tuning system / settings

### ISSUE THREAD

**Issue by AndyGrant** [AndyGrant/Ethereal#66]
* Depth 0 should actually correspond to Texel Tuning Proper (IE, no search)
* Depth 0 should not care about the CLEARING setting, as its never used, simply a slowdown
* The comment about CLEARING in ``texel.c`` is unclear, may suggest something other than intended.
* Option to collect the phase from before or after resolution of the position.
* No reason to have three sets of ``ENABLE_``, collapse with macro magic into the header
* Fix comment about scaling PawnValue[MG] to 100cp

**Comment by AlexGreason** [comment]
// Combine original and updated, scale so PawnValue[MG] = 100
There's this comment in printParameters, but the values aren't actually scaled
Relatedly, I didn't realize that it was tuning only an update to the parameters rather than the parameters themselves initially. That is documented, so I'm not sure what can be done about that, I just didn't notice the relevant bits until I'd already been told.

**Comment by AndyGrant** [comment]
``// Combine original and updated, scale so PawnValue[MG] = 100`` Yes, this is an old comment. I originally forced pawn MG to be 100, but I proved at some point that it was unsound.

**Comment by AndyGrant** [comment]
https://github.com/AndyGrant/Ethereal/commit/b204abc649348257fde46fe8544cc58a57d65616 resolved
